#!/usr/bin/env bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################
if [ -n "$APPDIR" ]; then
  export LD_LIBRARY_PATH=`sed -E "s,${APPDIR}/[^\:]+[\:^](\:|\$),,g" <<< $LD_LIBRARY_PATH`
fi
SWD=`dirname $(readlink -e $0)`
: ${BAMBU_HLS:="/tmp/.mount_bambu.w4mQjX/usr"}
BAMBU_HLS_OUTDIR="${SWD}"
BAMBU_HLS_RESULTS="${BAMBU_HLS_OUTDIR}/bambu_results.xml"
bambu_results() { xmlq "${BAMBU_HLS_RESULTS}" "$1"; }
export BAMBU_HLS
export BAMBU_HLS_OUTDIR
export BAMBU_HLS_RESULTS
export -f bambu_results
export PATH="${BAMBU_HLS_OUTDIR}/HLS_output/utils:${PATH}"

BACKENDS=()

BACKENDS+=("HLS_output/simulation/verilator_backend/launch.sh")
# BACKENDS+=("HLS_output/xilinx/flow_backend/launch.sh")

cd "${SWD}"
set -e
for backend in ${BACKENDS[@]};
do
  backend_dir=`dirname ${backend}`
  backend_log="${backend_dir}/launch.log"
  step_id=`basename $(dirname ${backend})`
  step_id="${step_id%%_backend}"
  step_id="${step_id//_/ }"
  step_results="${backend_dir}/`basename ${BAMBU_HLS_RESULTS}`"
  echo "BACKEND STEP ${step_id}"
  (./${backend} "$@" 2>&1 | tee "${backend_log}"; exit ${PIPESTATUS[0]})
  if [ -f "${step_results}" ]; then
    xmlmerge -i "${BAMBU_HLS_RESULTS}" "${step_results}"
  fi
done

